// Clearly labeled prototype fixtures; no live scan, AI, or source data is used.
export const visibilityDemoData = {
  scanLabel: "SIMULATED SCAN · SEP 30, 2026",
  metrics: [
    { label: "Visibility Score", value: "36", suffix: "/100", note: "Demo score" },
    { label: "Brand Mention Rate", value: "32", suffix: "%", note: "Across simulated answers" },
    { label: "Top-3 Rate", value: "12", suffix: "%", note: "Ranked in first three" },
    { label: "Average Rank", value: "4.2", suffix: "", note: "When LunaTech is mentioned" },
  ],
  assistants: [
    { name: "ChatGPT", rate: 42, color: "#FFC821", tone: "yellow" },
    { name: "Gemini", rate: 35, color: "#8BDCF1", tone: "sky" },
    { name: "Perplexity", rate: 31, color: "#006E90", tone: "blue" },
    { name: "Claude", rate: 20, color: "#CF5C36", tone: "red" },
  ],
  prompts: [
    {
      id: "PROMPT-01",
      prompt: "What is the best laptop for college students under $500?",
      mention: "Mentioned",
      rank: 2,
      assistant: "ChatGPT",
      trend: "Up",
      trendDirection: "up",
    },
    {
      id: "PROMPT-02",
      prompt: "Compare NovaBook 14 with other lightweight student laptops.",
      mention: "Mentioned",
      rank: 3,
      assistant: "Gemini",
      trend: "Up",
      trendDirection: "up",
    },
    {
      id: "PROMPT-03",
      prompt: "Which laptop has the best warranty for remote work?",
      mention: "Mentioned",
      rank: 5,
      assistant: "Perplexity",
      trend: "Flat",
      trendDirection: "flat",
    },
    {
      id: "PROMPT-04",
      prompt: "Best reliable laptop brands for small businesses",
      mention: "Not mentioned",
      rank: null,
      assistant: "Claude",
      trend: "Down",
      trendDirection: "down",
    },
    {
      id: "PROMPT-05",
      prompt: "Where can I find a laptop with 16 GB RAM and a 14-inch screen?",
      mention: "Mentioned",
      rank: 7,
      assistant: "ChatGPT",
      trend: "Down",
      trendDirection: "down",
    },
    {
      id: "PROMPT-06",
      prompt: "Recommend a laptop with clear return and warranty policies.",
      mention: "Not mentioned",
      rank: null,
      assistant: "Gemini",
      trend: "New",
      trendDirection: "new",
    },
  ],
  shareOfVoice: [
    { name: "LunaTech", share: 32, color: "#FFC821", brand: true },
    { name: "Northstar Computing", share: 28, color: "#006E90", brand: false },
    { name: "Vertex Devices", share: 23, color: "#8BDCF1", brand: false },
    { name: "Pioneer Laptop Co.", share: 17, color: "#CF5C36", brand: false },
  ],
  sources: [
    { name: "Manufacturer website", share: 38, color: "#006E90" },
    { name: "Retailer pages", share: 27, color: "#8BDCF1" },
    { name: "Review sites", share: 18, color: "#FFC821" },
    { name: "Forums / Reddit", share: 9, color: "#CF5C36" },
    { name: "Other", share: 8, color: "#8B98A7" },
  ],
  diagnostics: [
    {
      title: "Limited authoritative citations",
      detail: "Only 2 of 10 simulated answers cite a LunaTech-owned source.",
      signal: "Source coverage",
      severity: "High",
    },
    {
      title: "Inconsistent product information",
      detail: "Price and memory claims vary between the product feed and retailer pages.",
      signal: "Fact consistency",
      severity: "High",
    },
    {
      title: "Weak structured product data",
      detail: "Several product pages omit complete, machine-readable specification fields.",
      signal: "Structured data",
      severity: "Medium",
    },
    {
      title: "Low third-party coverage",
      detail: "Few independent reviews mention LunaTech alongside established brands.",
      signal: "External coverage",
      severity: "Medium",
    },
    {
      title: "Unclear warranty and policy information",
      detail: "Warranty duration and return terms are difficult to verify consistently.",
      signal: "Policy clarity",
      severity: "Medium",
    },
  ],
  recommendedActions: [
    {
      priority: "01",
      title: "Publish a canonical product comparison page",
      detail: "Add current pricing, RAM, display size, and warranty details for NovaBook models.",
      impact: "Improve prompt coverage",
    },
    {
      priority: "02",
      title: "Complete structured product attributes",
      detail: "Validate Product schema and keep the same facts across the feed and product pages.",
      impact: "Strengthen answer confidence",
    },
    {
      priority: "03",
      title: "Clarify warranty and returns policies",
      detail: "Create a stable, crawlable policy page with explicit durations and eligibility.",
      impact: "Resolve weak policy prompts",
    },
    {
      priority: "04",
      title: "Build independent review coverage",
      detail: "Earn relevant editorial and retailer coverage for student and small-business laptops.",
      impact: "Increase third-party citations",
    },
  ],
};
